version: '3'
services:
  web:
    build: .
    ports:
     - "3000:3000"
    volumes:
     - ./pages:/web/pages
     - ./components:/web/components
     - ./utils:/web/utils
     - ./public:/web/public
     - .env:/web/.env
    command: sh -c  "npm i && npm run dev"
